/**
 * Claude Code Plugin packaging (plan Fase 4, sleepy-singing-lobster).
 *
 * Generates a self-contained plugin directory — `.claude-plugin/plugin.json`
 * + `agents/*.md` + `hooks/hooks.json` + `.mcp.json` — from the same
 * `AGENT_DEFS` roster and hook/MCP shapes `aiyoucli init --tool claude`
 * already uses for the standalone `.claude/` path (`buildClaudeAgentFile`,
 * `buildClaudeSettings`, `buildMcpJson` — reused here, not re-derived).
 * This is the "shareable" path Claude Code's own docs recommend graduating
 * to: standalone `.claude/` for quick iteration, a plugin once you want to
 * share/version it — see https://code.claude.com/docs/en/plugins.
 *
 * Unlike the standalone files (written once, left alone unless `--force`),
 * `aiyoucli plugin build` always overwrites — the plugin is meant to be
 * rebuilt whenever the roster or a `aiyoucli agent set-model` override
 * changes, not hand-edited in place.
 *
 * What this adds beyond the standalone path:
 *   - SessionStart hook (`aiyoucli hooks session-start`): a short roster +
 *     "prefer the CLI" reminder injected as initial context — this is the
 *     concrete mechanism for "activating aiyoucli makes Claude Code use its
 *     agents" (the thing `.claude/` alone doesn't do — those files are
 *     inert until Claude Code happens to pick a matching `subagent_type`).
 *   - UserPromptSubmit hook (`aiyoucli hooks user-prompt-submit`): a
 *     routing hint from the existing Q-learning router
 *     (`hooks_pre_task`/`route`), emitted as `additionalContext` only above
 *     a confidence threshold — see that subcommand's own comments for why
 *     PreToolUse(Task) was considered and rejected (fires too late to
 *     influence which agent gets picked).
 *   - Everything `--with-hooks --with-agents` already wires for the
 *     standalone path (PreToolUse/PostToolUse Q-table observations),
 *     reused via `buildClaudeSettings(true).hooks`.
 *
 * Deliberately NOT included: a `bin/` directory shimming `aiyoucli`/
 * `aiyoucli-mcp` onto PATH. Cross-platform shims are fragile to get right;
 * the SessionStart hook already tells the user plainly if `aiyoucli` isn't
 * resolvable, which is simpler and doesn't risk shadowing a real install.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { AGENT_DEFS, buildClaudeAgentFile, buildDelegatingPromptBody } from "./claude-agents.js";
import { buildMcpJson, buildClaudeSettings } from "./settings-generator.js";
import { loadConfig } from "../config.js";
import { resolveRuntimeAndModel } from "../orchestrate/dispatch.js";
import { packageVersion } from "../version.js";

export interface GeneratePluginOptions {
  /** Absolute path to the plugin root, e.g. `<projectRoot>/.aiyou-team-plugin`. */
  outDir: string;
}

export interface GeneratePluginResult {
  pluginDir: string;
  files: string[];
}

function buildPluginManifest(): object {
  return {
    name: "aiyou-team",
    description: "aiyou-team's agent roster, routing hints, and MCP server for Claude Code — generated by aiyoucli.",
    version: packageVersion(),
  };
}

function buildPluginHooksJson(): object {
  const standaloneHooks = (buildClaudeSettings(true) as { hooks: Record<string, unknown> }).hooks;

  return {
    description: "aiyou-team lifecycle hooks — roster reminder, routing hints, Q-table observations.",
    hooks: {
      ...standaloneHooks,
      SessionStart: [
        {
          matcher: "startup",
          hooks: [{ type: "command", command: "aiyoucli hooks session-start", timeout: 10 }],
        },
      ],
      // No `matcher` — UserPromptSubmit isn't tool-scoped. Always exits 0
      // (informational; must never block/erase the user's prompt) — see
      // `aiyoucli hooks user-prompt-submit`'s own confidence gating for why
      // it usually prints nothing at all rather than being noisy.
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: "command",
              command:
                "node -e \"const d=JSON.parse(require('fs').readFileSync(0,'utf8')||'{}');" +
                "const{spawnSync}=require('child_process');" +
                "spawnSync('aiyoucli',['hooks','user-prompt-submit','--prompt',d.user_input||''],{stdio:'inherit'});" +
                "process.exit(0)\"",
              timeout: 15,
            },
          ],
        },
      ],
    },
  };
}

/**
 * Builds the full plugin file set as `{relativePath: content}` pairs,
 * without touching disk — kept pure so tests can assert on content without
 * a filesystem round-trip. `generatePlugin` below just writes these.
 */
export function buildPluginFiles(): Record<string, string> {
  const agentOverrides = loadConfig().agents;

  const files: Record<string, string> = {
    ".claude-plugin/plugin.json": JSON.stringify(buildPluginManifest(), null, 2) + "\n",
    "hooks/hooks.json": JSON.stringify(buildPluginHooksJson(), null, 2) + "\n",
    ".mcp.json": JSON.stringify(buildMcpJson(), null, 2) + "\n",
  };

  for (const def of AGENT_DEFS) {
    // Delegates to agy/opencode/mmx by default when installed — see
    // buildDelegatingPromptBody's header for the recursion-safety invariant.
    const { runtime } = resolveRuntimeAndModel(def.name);
    const delegatingDef = { ...def, promptBody: buildDelegatingPromptBody(def, runtime) };
    files[`agents/${def.name}.md`] = buildClaudeAgentFile(delegatingDef, agentOverrides?.[def.name]?.model);
  }

  return files;
}

export function generatePlugin(opts: GeneratePluginOptions): GeneratePluginResult {
  const files = buildPluginFiles();
  const written: string[] = [];

  for (const [relativePath, content] of Object.entries(files)) {
    const absolutePath = join(opts.outDir, relativePath);
    mkdirSync(join(absolutePath, ".."), { recursive: true });
    writeFileSync(absolutePath, content, "utf-8");
    written.push(absolutePath);
  }

  return { pluginDir: opts.outDir, files: written };
}
