/**
 * PDF → Markdown NAPI tests — vitest.
 * Fixture (`fixtures/sample.pdf`) is generated by pdfrs itself; regenerate
 * with `cargo test -p aiyoucli-napi -- --ignored regenerate_fixture`
 * (see crates/aiyoucli-napi/src/pdf.rs).
 */

import { describe, it, expect } from "vitest";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { pdfToMarkdown } from "../src/napi/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = join(__dirname, "fixtures", "sample.pdf");

describe("pdfToMarkdown (NAPI)", () => {
  it("converts a PDF's native text to Markdown", () => {
    const md = pdfToMarkdown(fixture);
    expect(md).toContain("Sample PDF");
    expect(md).toContain("Hello from pdfrs");
    expect(md).toContain("Notes");
    expect(md).toContain("one");
  });

  it("throws on a missing file", () => {
    expect(() => pdfToMarkdown("/nonexistent/does-not-exist.pdf")).toThrow();
  });
});
